package com.jobgun.aggregator.craigslist

object GeoCategories {
    val geo: Map[String, String] = Map(
        "abilene" -> "abilene, TX",
        "akroncanton" -> "akron / canton",
        "albanyga" -> "albany, GA",
        "albany" -> "albany, NY",
        "albuquerque" -> "albuquerque",
        "altoona" -> "altoona-johnstown",
        "amarillo" -> "amarillo, TX",
        "ames" -> "ames, IA",
        "anchorage" -> "anchorage / mat-su",
        "annapolis" -> "annapolis, MD",
        "annarbor" -> "ann arbor, MI",
        "appleton" -> "appleton-oshkosh-FDL",
        "asheville" -> "asheville, NC",
        "ashtabula" -> "ashtabula, OH",
        "athensga" -> "athens, GA",
        "athensohio" -> "athens, OH",
        "atlanta" -> "atlanta, GA",
        "auburn" -> "auburn, AL",
        "augusta" -> "augusta, GA",
        "austin" -> "austin, TX",
        "bakersfield" -> "bakersfield, CA",
        "baltimore" -> "baltimore, MD",
        "batonrouge" -> "baton rouge",
        "battlecreek" -> "battle creek, MI",
        "beaumont" -> "beaumont / port arthur",
        "bellingham" -> "bellingham, WA",
        "bemidji" -> "bemidji, MN",
        "bend" -> "bend, OR",
        "billings" -> "billings, MT",
        "binghamton" -> "binghamton, NY",
        "bham" -> "birmingham, AL",
        "bismarck" -> "bismarck, ND",
        "bloomington" -> "bloomington, IN",
        "bn" -> "bloomington-normal",
        "boise" -> "boise, ID",
        "boone" -> "boone, NC",
        "boston" -> "boston",
        "boulder" -> "boulder, CO",
        "bgky" -> "bowling green, KY",
        "bozeman" -> "bozeman, MT",
        "brainerd" -> "brainerd, MN",
        "brownsville" -> "brownsville, TX",
        "brunswick" -> "brunswick, GA",
        "buffalo" -> "buffalo, NY",
        "butte" -> "butte, MT",
        "capecod" -> "cape cod / islands",
        "catskills" -> "catskills",
        "cedarrapids" -> "cedar rapids, IA",
        "cenla" -> "central louisiana",
        "centralmich" -> "central michigan",
        "cnj" -> "central NJ",
        "chambana" -> "champaign urbana",
        "charleston" -> "charleston, SC",
        "charlestonwv" -> "charleston, WV",
        "charlotte" -> "charlotte, NC",
        "charlottesville" -> "charlottesville, VA",
        "chattanooga" -> "chattanooga, TN",
        "chautauqua" -> "chautauqua, NY",
        "chicago" -> "chicago",
        "chico" -> "chico, CA",
        "chillicothe" -> "chillicothe, OH",
        "cincinnati" -> "cincinnati, OH",
        "clarksville" -> "clarksville, TN",
        "cleveland" -> "cleveland, OH",
        "clovis" -> "clovis / portales",
        "collegestation" -> "college station, TX",
        "cosprings" -> "colorado springs",
        "columbiamo" -> "columbia / jeff city",
        "columbia" -> "columbia, SC",
        "columbusga" -> "columbus, GA",
        "columbus" -> "columbus, OH",
        "cookeville" -> "cookeville, TN",
        "corpuschristi" -> "corpus christi, TX",
        "corvallis" -> "corvallis/albany",
        "chambersburg" -> "cumberland valley",
        "dallas" -> "dallas / fort worth",
        "danville" -> "danville",
        "daytona" -> "daytona beach",
        "dayton" -> "dayton / springfield",
        "decatur" -> "decatur, IL",
        "nacogdoches" -> "deep east texas",
        "delaware" -> "delaware",
        "delrio" -> "del rio / eagle pass",
        "denver" -> "denver, CO",
        "desmoines" -> "des moines, IA",
        "detroit" -> "detroit metro",
        "dothan" -> "dothan, AL",
        "dubuque" -> "dubuque",
        "duluth" -> "duluth / superior",
        "eastco" -> "eastern CO",
        "newlondon" -> "eastern CT",
        "eastky" -> "eastern kentucky",
        "montana" -> "eastern montana",
        "eastnc" -> "eastern NC",
        "martinsburg" -> "eastern panhandle",
        "easternshore" -> "eastern shore",
        "eastidaho" -> "east idaho",
        "eastoregon" -> "east oregon",
        "eauclaire" -> "eau claire, WI",
        "elko" -> "elko, NV",
        "elmira" -> "elmira-corning",
        "elpaso" -> "el paso, TX",
        "erie" -> "erie, PA",
        "eugene" -> "eugene, OR",
        "evansville" -> "evansville, IN",
        "fairbanks" -> "fairbanks, AK",
        "fargo" -> "fargo / moorhead",
        "farmington" -> "farmington, NM",
        "fayar" -> "fayetteville, AR",
        "fayetteville" -> "fayetteville, NC",
        "fingerlakes" -> "finger lakes, NY",
        "flagstaff" -> "flagstaff / sedona",
        "flint" -> "flint, MI",
        "shoals" -> "florence / muscle shoals",
        "florencesc" -> "florence, SC",
        "keys" -> "florida keys",
        "fortcollins" -> "fort collins / north CO",
        "fortdodge" -> "fort dodge, IA",
        "fortsmith" -> "fort smith, AR",
        "fortwayne" -> "fort wayne, IN",
        "frederick" -> "frederick, MD",
        "fredericksburg" -> "fredericksburg, VA",
        "fresno" -> "fresno / madera",
        "fortmyers" -> "ft myers / SW florida",
        "gadsden" -> "gadsden-anniston",
        "gainesville" -> "gainesville, FL",
        "galveston" -> "galveston, TX",
        "glensfalls" -> "glens falls, NY",
        "goldcountry" -> "gold country",
        "grandforks" -> "grand forks",
        "grandisland" -> "grand island, NE",
        "grandrapids" -> "grand rapids, MI",
        "greatfalls" -> "great falls, MT",
        "greenbay" -> "green bay, WI",
        "greensboro" -> "greensboro, NC",
        "greenville" -> "greenville / upstate",
        "gulfport" -> "gulfport / biloxi",
        "hanford" -> "hanford-corcoran",
        "harrisburg" -> "harrisburg, PA",
        "harrisonburg" -> "harrisonburg, VA",
        "hartford" -> "hartford, CT",
        "hattiesburg" -> "hattiesburg, MS",
        "honolulu" -> "hawaii",
        "cfl" -> "heartland florida",
        "helena" -> "helena, MT",
        "hickory" -> "hickory / lenoir",
        "rockies" -> "high rockies",
        "hiltonhead" -> "hilton head",
        "holland" -> "holland, MI",
        "houma" -> "houma, LA",
        "houston" -> "houston, TX",
        "hudsonvalley" -> "hudson valley, NY",
        "humboldt" -> "humboldt county",
        "huntington" -> "huntington-ashland",
        "huntsville" -> "huntsville / decatur",
        "imperial" -> "imperial county",
        "indianapolis" -> "indianapolis",
        "inlandempire" -> "inland empire, CA",
        "iowacity" -> "iowa city, IA",
        "ithaca" -> "ithaca, NY",
        "jxn" -> "jackson, MI",
        "jackson" -> "jackson, MS",
        "jacksontn" -> "jackson, TN",
        "jacksonville" -> "jacksonville, FL",
        "onslow" -> "jacksonville, NC",
        "janesville" -> "janesville, WI",
        "jerseyshore" -> "jersey shore",
        "jonesboro" -> "jonesboro, AR",
        "joplin" -> "joplin, MO",
        "kalamazoo" -> "kalamazoo, MI",
        "kalispell" -> "kalispell, MT",
        "kansascity" -> "kansas city, MO",
        "kenai" -> "kenai peninsula",
        "kpr" -> "kennewick-pasco-richland",
        "racine" -> "kenosha-racine",
        "killeen" -> "killeen / temple / ft hood",
        "kirksville" -> "kirksville, MO",
        "klamath" -> "klamath falls, OR",
        "knoxville" -> "knoxville, TN",
        "kokomo" -> "kokomo, IN",
        "lacrosse" -> "la crosse, WI",
        "lafayette" -> "lafayette, LA",
        "tippecanoe" -> "lafayette / west lafayette",
        "lakecharles" -> "lake charles, LA",
        "lakeland" -> "lakeland, FL",
        "loz" -> "lake of the ozarks",
        "lancaster" -> "lancaster, PA",
        "lansing" -> "lansing, MI",
        "laredo" -> "laredo, TX",
        "lasalle" -> "la salle co",
        "lascruces" -> "las cruces, NM",
        "lasvegas" -> "las vegas",
        "lawrence" -> "lawrence, KS",
        "lawton" -> "lawton, OK",
        "allentown" -> "lehigh valley",
        "lewiston" -> "lewiston / clarkston",
        "lexington" -> "lexington, KY",
        "limaohio" -> "lima / findlay",
        "lincoln" -> "lincoln, NE",
        "littlerock" -> "little rock",
        "logan" -> "logan, UT",
        "longisland" -> "long island, NY",
        "losangeles" -> "los angeles",
        "louisville" -> "louisville, KY",
        "lubbock" -> "lubbock, TX",
        "lynchburg" -> "lynchburg, VA",
        "macon" -> "macon / warner robins",
        "madison" -> "madison, WI",
        "maine" -> "maine",
        "ksu" -> "manhattan, KS",
        "mankato" -> "mankato, MN",
        "mansfield" -> "mansfield, OH",
        "masoncity" -> "mason city, IA",
        "mattoon" -> "mattoon-charleston",
        "mcallen" -> "mcallen / edinburg",
        "meadville" -> "meadville, PA",
        "medford" -> "medford-ashland",
        "memphis" -> "memphis, TN",
        "mendocino" -> "mendocino county",
        "merced" -> "merced, CA",
        "meridian" -> "meridian, MS",
        "milwaukee" -> "milwaukee, WI",
        "minneapolis" -> "minneapolis / st paul",
        "missoula" -> "missoula, MT",
        "mobile" -> "mobile, AL",
        "modesto" -> "modesto, CA",
        "mohave" -> "mohave county",
        "monroe" -> "monroe, LA",
        "monroemi" -> "monroe, MI",
        "monterey" -> "monterey bay",
        "montgomery" -> "montgomery, AL",
        "morgantown" -> "morgantown, WV",
        "moseslake" -> "moses lake, WA",
        "muncie" -> "muncie / anderson",
        "muskegon" -> "muskegon, MI",
        "myrtlebeach" -> "myrtle beach, SC",
        "nashville" -> "nashville, TN",
        "nh" -> "new hampshire",
        "newhaven" -> "new haven, CT",
        "neworleans" -> "new orleans",
        "blacksburg" -> "new river valley",
        "newyork" -> "new york city",
        "norfolk" -> "norfolk / hampton roads",
        "lakecity" -> "north central FL",
        "nd" -> "north dakota",
        "nesd" -> "northeast SD",
        "nmi" -> "northern michigan",
        "wheeling" -> "northern panhandle",
        "northernwi" -> "northern WI",
        "newjersey" -> "north jersey",
        "northmiss" -> "north mississippi",
        "northplatte" -> "north platte, NE",
        "nwct" -> "northwest CT",
        "nwga" -> "northwest GA",
        "nwks" -> "northwest KS",
        "enid" -> "northwest OK",
        "ocala" -> "ocala, FL",
        "odessa" -> "odessa / midland",
        "ogden" -> "ogden-clearfield",
        "okaloosa" -> "okaloosa / walton",
        "oklahomacity" -> "oklahoma city",
        "olympic" -> "olympic peninsula",
        "omaha" -> "omaha / council bluffs",
        "oneonta" -> "oneonta, NY",
        "orangecounty" -> "orange county, CA",
        "oregoncoast" -> "oregon coast",
        "orlando" -> "orlando, FL",
        "outerbanks" -> "outer banks",
        "owensboro" -> "owensboro, KY",
        "palmsprings" -> "palm springs, CA",
        "panamacity" -> "panama city, FL",
        "parkersburg" -> "parkersburg-marietta",
        "pensacola" -> "pensacola, FL",
        "peoria" -> "peoria, IL",
        "philadelphia" -> "philadelphia",
        "phoenix" -> "phoenix, AZ",
        "csd" -> "pierre / central SD",
        "pittsburgh" -> "pittsburgh, PA",
        "plattsburgh" -> "plattsburgh-adirondacks",
        "poconos" -> "poconos",
        "porthuron" -> "port huron, MI",
        "portland" -> "portland, OR",
        "potsdam" -> "potsdam-canton-massena",
        "prescott" -> "prescott, AZ",
        "provo" -> "provo / orem",
        "pueblo" -> "pueblo, CO",
        "pullman" -> "pullman / moscow",
        "quadcities" -> "quad cities, IA/IL",
        "raleigh" -> "raleigh / durham / CH",
        "rapidcity" -> "rapid city / west SD",
        "reading" -> "reading, PA",
        "redding" -> "redding, CA",
        "reno" -> "reno / tahoe",
        "providence" -> "rhode island",
        "richmondin" -> "richmond, IN",
        "richmond" -> "richmond, VA",
        "roanoke" -> "roanoke, VA",
        "rmn" -> "rochester, MN",
        "rochester" -> "rochester, NY",
        "rockford" -> "rockford, IL",
        "roseburg" -> "roseburg, OR",
        "roswell" -> "roswell / carlsbad",
        "sacramento" -> "sacramento",
        "saginaw" -> "saginaw-midland-baycity",
        "salem" -> "salem, OR",
        "salina" -> "salina, KS",
        "saltlakecity" -> "salt lake city",
        "sanangelo" -> "san angelo, TX",
        "sanantonio" -> "san antonio",
        "sandiego" -> "san diego",
        "sandusky" -> "sandusky, OH",
        "slo" -> "san luis obispo",
        "sanmarcos" -> "san marcos, TX",
        "santabarbara" -> "santa barbara",
        "santafe" -> "santa fe / taos",
        "santamaria" -> "santa maria, CA",
        "sarasota" -> "sarasota-bradenton",
        "savannah" -> "savannah / hinesville",
        "scottsbluff" -> "scottsbluff / panhandle",
        "scranton" -> "scranton / wilkes-barre",
        "seattle" -> "seattle-tacoma",
        "sfbay" -> "SF bay area",
        "sheboygan" -> "sheboygan, WI",
        "showlow" -> "show low, AZ",
        "shreveport" -> "shreveport, LA",
        "sierravista" -> "sierra vista, AZ",
        "siouxcity" -> "sioux city, IA",
        "siouxfalls" -> "sioux falls / SE SD",
        "siskiyou" -> "siskiyou county",
        "skagit" -> "skagit / island / SJI",
        "southbend" -> "south bend / michiana",
        "southcoast" -> "south coast, MA",
        "sd" -> "south dakota",
        "juneau" -> "southeast alaska",
        "ottumwa" -> "southeast IA",
        "seks" -> "southeast KS",
        "semo" -> "southeast missouri",
        "carbondale" -> "southern illinois",
        "smd" -> "southern maryland",
        "swv" -> "southern WV",
        "miami" -> "south florida",
        "southjersey" -> "south jersey",
        "swks" -> "southwest KS",
        "swmi" -> "southwest michigan",
        "marshall" -> "southwest MN",
        "natchez" -> "southwest MS",
        "bigbend" -> "southwest TX",
        "swva" -> "southwest VA",
        "spacecoast" -> "space coast, FL",
        "spokane" -> "spokane / coeur d'alene",
        "springfieldil" -> "springfield, IL",
        "springfield" -> "springfield, MO",
        "pennstate" -> "state college, PA",
        "statesboro" -> "statesboro, GA",
        "staugustine" -> "st augustine, FL",
        "stcloud" -> "st cloud, MN",
        "stgeorge" -> "st george, UT",
        "stillwater" -> "stillwater, OK",
        "stjoseph" -> "st joseph",
        "stlouis" -> "st louis, MO",
        "stockton" -> "stockton, CA",
        "susanville" -> "susanville, CA",
        "syracuse" -> "syracuse, NY",
        "tallahassee" -> "tallahassee",
        "tampa" -> "tampa bay area",
        "terrehaute" -> "terre haute, IN",
        "texarkana" -> "texarkana",
        "texoma" -> "texoma",
        "thumb" -> "the thumb, MI",
        "toledo" -> "toledo, OH",
        "topeka" -> "topeka, KS",
        "treasure" -> "treasure coast, FL",
        "tricities" -> "tri-cities, TN",
        "tucson" -> "tucson, AZ",
        "tulsa" -> "tulsa, OK",
        "tuscaloosa" -> "tuscaloosa",
        "tuscarawas" -> "tuscarawas co",
        "twinfalls" -> "twin falls, ID",
        "twintiers" -> "twin tiers NY/PA",
        "easttexas" -> "tyler / east TX",
        "up" -> "upper peninsula, MI",
        "utica" -> "utica-rome-oneida",
        "valdosta" -> "valdosta, GA",
        "ventura" -> "ventura county",
        "vermont" -> "vermont",
        "victoriatx" -> "victoria, TX",
        "visalia" -> "visalia-tulare",
        "waco" -> "waco, TX",
        "washingtondc" -> "washington, DC",
        "waterloo" -> "waterloo / cedar falls",
        "watertown" -> "watertown, NY",
        "wausau" -> "wausau, WI",
        "wenatchee" -> "wenatchee, WA",
        "quincy" -> "western IL",
        "westky" -> "western KY",
        "westmd" -> "western maryland",
        "westernmass" -> "western massachusetts",
        "westslope" -> "western slope",
        "wv" -> "west virginia (old)",
        "wichitafalls" -> "wichita falls, TX",
        "wichita" -> "wichita, KS",
        "williamsport" -> "williamsport, PA",
        "wilmington" -> "wilmington, NC",
        "winchester" -> "winchester, VA",
        "winstonsalem" -> "winston-salem, NC",
        "worcester" -> "worcester / central MA",
        "wyoming" -> "wyoming",
        "yakima" -> "yakima, WA",
        "york" -> "york, PA",
        "youngstown" -> "youngstown, OH",
        "yubasutter" -> "yuba-sutter, CA",
        "yuma" -> "yuma, AZ"
    )
}